# Pipeline name convention
name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

# Trigger configuration
trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

# Parameters
parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

# Resources
resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-709   # Optional: build specific pipeline branch

# Pipeline template
extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs   # Optional: nodejs (default), dotnet, java
    Type: kubernetes           # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false   # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    # failOnThreshold: moderate
    variableGroupName: ffc-doc-statement-publisher-env-var
    pr_params:
      sendCrmFailureMessageEnabled: ${{ eq(variables['pr_sendCrmFailureMessageEnabled'], 'true') }}
      deliveryCheckInterval: $(pr_deliveryCheckInterval)
      metricsPollingInterval: $(pr_pmetricsPollingInterval)
      notifyApiKey: $(pr_notifyApiKey)
      notifyApiKeyLetter: $(pr_notifyApiKeyLetter)
      reportingCheckInterval: $(pr_reportingCheckInterval)
    snd2_params:
      sendCrmFailureMessageEnabled: ${{ eq(variables['snd2_sendCrmFailureMessageEnabled'], 'true') }}
      deliveryCheckInterval: $(snd2_deliveryCheckInterval)
      metricsPollingInterval: $(snd2_pmetricsPollingInterval)
      notifyApiKey: $(snd2_notifyApiKey)
      notifyApiKeyLetter: $(snd2_notifyApiKeyLetter)
      reportingCheckInterval: $(snd2_reportingCheckInterval)
    dev_params:
      sendCrmFailureMessageEnabled: ${{ eq(variables['dev_sendCrmFailureMessageEnabled'], 'true') }}
      deliveryCheckInterval: $(dev_deliveryCheckInterval)
      metricsPollingInterval: $(dev_pmetricsPollingInterval)
      notifyApiKey: $(dev_notifyApiKey)
      notifyApiKeyLetter: $(dev_notifyApiKeyLetter)
      reportingCheckInterval: $(dev_reportingCheckInterval)
    test_params:
      sendCrmFailureMessageEnabled: ${{ eq(variables['test_sendCrmFailureMessageEnabled'], 'true') }}
      deliveryCheckInterval: $(test_deliveryCheckInterval)
      metricsPollingInterval: $(test_pmetricsPollingInterval)
      notifyApiKey: $(test_notifyApiKey)
      notifyApiKeyLetter: $(test_notifyApiKeyLetter)
      reportingCheckInterval: $(test_reportingCheckInterval)
    pre_params:
      sendCrmFailureMessageEnabled: ${{ eq(variables['pre_sendCrmFailureMessageEnabled'], 'true') }}
      deliveryCheckInterval: $(pre_deliveryCheckInterval)
      metricsPollingInterval: $(pre_pmetricsPollingInterval)
      notifyApiKey: $(pre_notifyApiKey)
      notifyApiKeyLetter: $(pre_notifyApiKeyLetter)
      reportingCheckInterval: $(pre_reportingCheckInterval)
    prd_params:
      sendCrmFailureMessageEnabled: ${{ eq(variables['prd_sendCrmFailureMessageEnabled'], 'true') }}
      deliveryCheckInterval: $(prd_deliveryCheckInterval)
      metricsPollingInterval: $(prd_pmetricsPollingInterval)
      notifyApiKey: $(prd_notifyApiKey)
      notifyApiKeyLetter: $(prd_notifyApiKeyLetter)
      reportingCheckInterval: $(prd_reportingCheckInterval)
