apiVersion: v2
description: Publish statements
name: ffc-doc-statement-publisher
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 5.1.4
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
